[save]
root = "/data/blanka/runs/RL/YOLOv8x/extra2"

[spn]
root = "/data/blanka/runs/SPN/YOLOv8x/prevfeat_modelwise_shifted_zerofilled_extra/20250724_115244_571837"
data_path = "/data/blanka/DATASETS/SPN/YOLOv8x" #original data folder (needed for alpha info)

[yolo]
samples_conf_path = "/data/blanka/DATASETS/SPN/YOLOv8x/settings.ini"

[model]
pretrained = ""
do_resume = True # if True, all the following params are irrelevant, as settings.ini will be loaded from the pretrained model
state_features = ['prev_n_params', 'prev_map50']
actor_optimizer = "adam" # ["adam". "lamb"]
actor_init_lr = 0.06
actor_weight_decay = 0.0007
actor_entropy_coef = 0.0007
critic_optimizer = 'adam'
critic_init_lr = 0.06
critic_weight_decay = 0.0007
lr_scheduler = 'cos'

[train]
seed = 42
episodes = 300
batch_size = 2
device = 'cuda'
do_folder_logging = True
save_interval = 10

[reward]
type = 'proposed'
target_spars = 0.7
target_dmap = 0.05
spars_coeff = 0.3
dmap_coeff = 0.7
beta = 5


; type = "purl" 
; target_spars = 0.6
; target_map = 0.8
; map_before = 0.9
; beta = 5



