[data]
root = "/data/blanka/DATASETS/SPN/YOLOv8x_newsplit/original_extended"
is_read_from_cache = False
cache_fantasy_name = "just_extra_features"

[save]
root = "/data/blanka/runs/SPN/YOLOv8x/extended_features"

[model]
pretrained = ''
do_resume = False
state_features = [  'alpha',
                    'is_pruned', 
                    ; 'in_ch',
                    ; 'out_ch',
                    ; 'kernel',
                    ; 'stride',
                    ; 'pad',
                    ; 'n_pruned_ch',
                    'prev_n_params',
                    'prev_map50'
                ]
n_prunable_layers =  93 
loss = "logcosh" # [mse, logcosh]
do_freeze_backend = False
do_freeze_head_spars = False
do_freeze_head_dmap = False
dmap_loss_weight = 1
spars_loss_weight = 1
optimizer = "adam" # [adam]
lr_scheduler = "cos" # [cos]
start_lr = 0.009
weight_decay = 5e-06

[train]
seed = 42
epochs = 600
batch_size = 256
device = 'cuda'
val_freq = 1

[alpha]
min_max_steps = [0, 2.2, 12] # min, max, n_steps