[data]
root = '/data/blanka/DATASETS/SPN/YOLOv8x_7030_shifted_zerofilled_extra'
is_read_from_cache = True
cache_fantasy_name = ''

[save]
root = '/data/blanka/runs/SPN/YOLOv8x/prevfeat_shifted_zerofilled_extra_transf'

[model]
pretrained = ''
do_resume = False
state_features = [  'alpha',
                    ; 'is_pruned', 
                    ; 'in_ch',
                    ; 'out_ch',
                    ; 'kernel',
                    ; 'stride',
                    ; 'pad',
                    ; 'n_pruned_ch',
                    'prev_n_params',
                    'prev_map50'
                ]
type = "transformer" # [basic, multihead, transformer]
model_dim = 64
num_heads = 4
num_layers = 2
dropout = 0.1
n_prunable_layers = 93
loss = 'logcosh'
do_freeze_backend = False
do_freeze_head_spars = False
do_freeze_head_dmap = False
dmap_loss_weight = 1
spars_loss_weight = 1
optimizer = 'adamw'
lr_scheduler = 'cos'
start_lr = 0.0008
weight_decay = 0.1

[train]
seed = 42
epochs = 100
batch_size = 256
device = 'cuda'
val_freq = 1

[alpha]
min_max_steps = [0, 2.2, 12]